# Generated by Django 5.1.7 on 2025-04-21 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('sandwich', 'Sandwich'), ('boisson', 'Boisson'), ('snack', 'Snack')], default='snack', max_length=50)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_cash', models.FloatField()),
                ('gain_card', models.FloatField()),
                ('gain_cash', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.article')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.article')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='users_custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='No Defined', max_length=255)),
                ('last_name', models.CharField(default='No Defined', max_length=255)),
                ('sold', models.FloatField(default=0)),
                ('class_name', models.CharField(default='No Defined', max_length=255)),
                ('nb_transaction', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('respo', 'Responsable'), ('student', 'Étudiant')], default='student', max_length=50)),
                ('status', models.CharField(choices=[('cotisant', 'Cotisant'), ('non_cotisant', 'Non Cotisant'), ('prof', 'Professeur')], default='non_cotisant', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
